services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: detomsite-backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
